version: '3.8'

services:
  apiserver:
    build: ./apiserver
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
      - opensearch
    volumes:
      - ./data:/app/data
      - ./ingestion:/app/ingestion

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: predator_db
      POSTGRES_USER: predator
      POSTGRES_PASSWORD: strong_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - cluster.name=predator-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - osdata:/usr/share/opensearch/data
      - ./backups/opensearch:/usr/share/opensearch/backup

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - lokidata:/loki

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.1.2
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=strong_password
    volumes:
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/dashboards/predator_dashboard.json:/var/lib/grafana/dashboards/predator_dashboard.json

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_API_BASE_URL=${OLLAMA_HOST:-http://host.docker.internal:11434}
    depends_on:
      - apiserver

volumes:
  pgdata:
  osdata:
  lokidata: