version: '3.8'

services:
  apiserver:
    build: ./apiserver
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}
      - MAX_CONTEXT_LENGTH=${MAX_CONTEXT_LENGTH:-2048}
      - OPENSEARCH_BULK_SIZE=${OPENSEARCH_BULK_SIZE:-500}
      - MAX_FILE_SIZE=1073741824  # 1 GB
      - API_PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
      - opensearch
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    restart: unless-stopped
    networks:
      - predator-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=predator_db
      - POSTGRES_USER=predator
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-strong_password}  # Використовуємо значення за замовчуванням
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U predator -d predator_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    restart: unless-stopped
    networks:
      - predator-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-your_redis_password}  # Використовуємо значення за замовчуванням
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: unless-stopped
    networks:
      - predator-network

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - cluster.name=predator-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - osdata:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    restart: unless-stopped
    networks:
      - predator-network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://apiserver:5001
      - FORCE_OLLAMA_API_BASE_URL=true
      - ENABLE_OLLAMA_API=true
      - STREAMING_ENABLED=true
    depends_on:
      apiserver:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - openwebui-data:/app/backend/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: unless-stopped
    networks:
      - predator-network

volumes:
  pgdata:
  osdata:
  openwebui-data:

networks:
  predator-network:
    driver: bridge