services:
  apiserver:
    build: ./apiserver
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - OLLAMA_HOST=${OLLAMA_HOST:-http://localhost:11434}
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
      - opensearch
    volumes:
      - ./data:/app/data
      - ./ingestion:/app/ingestion
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: predator_db
      POSTGRES_USER: predator
      POSTGRES_PASSWORD: strong_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U predator"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - cluster.name=predator-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - osdata:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=${OLLAMA_HOST:-http://host.docker.internal:11434}
    depends_on:
      - apiserver
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: unless-stopped

volumes:
  pgdata:
  osdata: