global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'apiserver'
    static_configs:
      - targets: ['apiserver:5001']  # Змініть порт, якщо ваш apiserver експортує метрики